spring:
  profiles:
    active: eureka1
---
server:
  port: 8761
spring:
  config:
    activate:
      on-profile: eureka1
  application:
    name: spring-cloud-eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka
---
server:
  port: 8762
spring:
  config:
    activate:
      on-profile: eureka2
  application:
    name: spring-cloud-eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
